[2022-08-23 21:40:45,461] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.01_cria_tabela manual__2022-08-23T21:40:43.506636+00:00 [queued]>
[2022-08-23 21:40:45,474] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.01_cria_tabela manual__2022-08-23T21:40:43.506636+00:00 [queued]>
[2022-08-23 21:40:45,475] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 21:40:45,476] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-23 21:40:45,476] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 21:40:45,498] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): 01_cria_tabela> on 2022-08-23 21:40:43.506636+00:00
[2022-08-23 21:40:45,504] {standard_task_runner.py:52} INFO - Started process 92 to run task
[2022-08-23 21:40:45,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'raizen_lab_01', '01_cria_tabela', 'manual__2022-08-23T21:40:43.506636+00:00', '--job-id', '9398', '--raw', '--subdir', 'DAGS_FOLDER/raizen_lab_01.py', '--cfg-path', '/tmp/tmprs1kkxod', '--error-file', '/tmp/tmpgdium2be']
[2022-08-23 21:40:45,510] {standard_task_runner.py:80} INFO - Job 9398: Subtask 01_cria_tabela
[2022-08-23 21:40:45,615] {task_command.py:371} INFO - Running <TaskInstance: raizen_lab_01.01_cria_tabela manual__2022-08-23T21:40:43.506636+00:00 [running]> on host 80fce776ee1f
[2022-08-23 21:40:45,740] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=raizen_lab_01
AIRFLOW_CTX_TASK_ID=01_cria_tabela
AIRFLOW_CTX_EXECUTION_DATE=2022-08-23T21:40:43.506636+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-23T21:40:43.506636+00:00
[2022-08-23 21:40:45,742] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/raizen_lab_01.py", line 34, in cria_tabela
    con = MySQLdb.connect(host="mysql", user="user", passwd="password", db="db")
NameError: name 'MySQLdb' is not defined
[2022-08-23 21:40:45,761] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=raizen_lab_01, task_id=01_cria_tabela, execution_date=20220823T214043, start_date=20220823T214045, end_date=20220823T214045
[2022-08-23 21:40:45,784] {standard_task_runner.py:97} ERROR - Failed to execute job 9398 for task 01_cria_tabela (name 'MySQLdb' is not defined; 92)
[2022-08-23 21:40:45,802] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-23 21:40:45,859] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
