[2022-08-23 18:54:49,729] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-22T20:00:00+00:00 [queued]>
[2022-08-23 18:54:49,833] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-22T20:00:00+00:00 [queued]>
[2022-08-23 18:54:49,842] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 18:54:49,844] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-08-23 18:54:49,848] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 18:54:49,944] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conecta_no_mysql> on 2022-01-22 20:00:00+00:00
[2022-08-23 18:54:50,019] {standard_task_runner.py:52} INFO - Started process 107 to run task
[2022-08-23 18:54:50,015] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'raizen_lab_01', 'conecta_no_mysql', 'scheduled__2022-01-22T20:00:00+00:00', '--job-id', '9032', '--raw', '--subdir', 'DAGS_FOLDER/raizen_lab_01.py', '--cfg-path', '/tmp/tmp9d6x92id', '--error-file', '/tmp/tmp2too3708']
[2022-08-23 18:54:50,067] {standard_task_runner.py:80} INFO - Job 9032: Subtask conecta_no_mysql
[2022-08-23 18:54:50,762] {task_command.py:371} INFO - Running <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-22T20:00:00+00:00 [running]> on host 292788567df6
[2022-08-23 18:54:51,287] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=raizen_lab_01
AIRFLOW_CTX_TASK_ID=conecta_no_mysql
AIRFLOW_CTX_EXECUTION_DATE=2022-01-22T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-22T20:00:00+00:00
[2022-08-23 18:55:01,358] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/raizen_lab_01.py", line 38, in conecta_no_mysql
    con = MySQLdb.connect(host="mysql", user="airflow_user", passwd="airflow_pass", db="airflow_db")
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'mysql' (-3)")
[2022-08-23 18:55:01,371] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=raizen_lab_01, task_id=conecta_no_mysql, execution_date=20220122T200000, start_date=20220823T185449, end_date=20220823T185501
[2022-08-23 18:55:01,390] {standard_task_runner.py:97} ERROR - Failed to execute job 9032 for task conecta_no_mysql ((2005, "Unknown MySQL server host 'mysql' (-3)"); 107)
[2022-08-23 18:55:01,438] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-23 18:55:01,480] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
