[2022-08-23 17:34:29,710] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-14T13:00:00+00:00 [queued]>
[2022-08-23 17:34:29,717] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-14T13:00:00+00:00 [queued]>
[2022-08-23 17:34:29,718] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 17:34:29,718] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-23 17:34:29,719] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 17:34:29,733] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conecta_no_mysql> on 2022-01-14 13:00:00+00:00
[2022-08-23 17:34:29,740] {standard_task_runner.py:52} INFO - Started process 181 to run task
[2022-08-23 17:34:29,742] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'raizen_lab_01', 'conecta_no_mysql', 'scheduled__2022-01-14T13:00:00+00:00', '--job-id', '8598', '--raw', '--subdir', 'DAGS_FOLDER/raizen_lab_01.py', '--cfg-path', '/tmp/tmpc34v7q8y', '--error-file', '/tmp/tmp1jgfgv6d']
[2022-08-23 17:34:29,744] {standard_task_runner.py:80} INFO - Job 8598: Subtask conecta_no_mysql
[2022-08-23 17:34:29,807] {task_command.py:371} INFO - Running <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-14T13:00:00+00:00 [running]> on host 8d054a683dd2
[2022-08-23 17:34:29,872] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=raizen_lab_01
AIRFLOW_CTX_TASK_ID=conecta_no_mysql
AIRFLOW_CTX_EXECUTION_DATE=2022-01-14T13:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-14T13:00:00+00:00
[2022-08-23 17:34:39,881] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/raizen_lab_01.py", line 35, in conecta_no_mysql
    con = MySQLdb.connect(host="mysql", user="user", passwd="password", db="db")
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'mysql' (-3)")
[2022-08-23 17:34:39,892] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=raizen_lab_01, task_id=conecta_no_mysql, execution_date=20220114T130000, start_date=20220823T173429, end_date=20220823T173439
[2022-08-23 17:34:39,905] {standard_task_runner.py:97} ERROR - Failed to execute job 8598 for task conecta_no_mysql ((2005, "Unknown MySQL server host 'mysql' (-3)"); 181)
[2022-08-23 17:34:39,913] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-23 17:34:39,939] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
