[2022-08-23 18:55:17,316] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-23T14:00:00+00:00 [queued]>
[2022-08-23 18:55:17,328] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-23T14:00:00+00:00 [queued]>
[2022-08-23 18:55:17,329] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 18:55:17,330] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-23 18:55:17,330] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 18:55:17,351] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conecta_no_mysql> on 2022-01-23 14:00:00+00:00
[2022-08-23 18:55:17,361] {standard_task_runner.py:52} INFO - Started process 173 to run task
[2022-08-23 18:55:17,366] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'raizen_lab_01', 'conecta_no_mysql', 'scheduled__2022-01-23T14:00:00+00:00', '--job-id', '9055', '--raw', '--subdir', 'DAGS_FOLDER/raizen_lab_01.py', '--cfg-path', '/tmp/tmpmm4tct5n', '--error-file', '/tmp/tmpbcn9r07a']
[2022-08-23 18:55:17,368] {standard_task_runner.py:80} INFO - Job 9055: Subtask conecta_no_mysql
[2022-08-23 18:55:17,462] {task_command.py:371} INFO - Running <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-23T14:00:00+00:00 [running]> on host 292788567df6
[2022-08-23 18:55:17,553] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=raizen_lab_01
AIRFLOW_CTX_TASK_ID=conecta_no_mysql
AIRFLOW_CTX_EXECUTION_DATE=2022-01-23T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-23T14:00:00+00:00
[2022-08-23 18:55:21,443] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/raizen_lab_01.py", line 38, in conecta_no_mysql
    con = MySQLdb.connect(host="mysql", user="airflow_user", passwd="airflow_pass", db="airflow_db")
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'mysql' (-2)")
[2022-08-23 18:55:21,455] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=raizen_lab_01, task_id=conecta_no_mysql, execution_date=20220123T140000, start_date=20220823T185517, end_date=20220823T185521
[2022-08-23 18:55:21,469] {standard_task_runner.py:97} ERROR - Failed to execute job 9055 for task conecta_no_mysql ((2005, "Unknown MySQL server host 'mysql' (-2)"); 173)
[2022-08-23 18:55:21,485] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-23 18:55:21,533] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
