[2022-08-23 19:31:57,317] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-26T12:00:00+00:00 [queued]>
[2022-08-23 19:31:57,331] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-26T12:00:00+00:00 [queued]>
[2022-08-23 19:31:57,332] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 19:31:57,335] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-23 19:31:57,336] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 19:31:57,357] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conecta_no_mysql> on 2022-01-26 12:00:00+00:00
[2022-08-23 19:31:57,365] {standard_task_runner.py:52} INFO - Started process 142 to run task
[2022-08-23 19:31:57,371] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'raizen_lab_01', 'conecta_no_mysql', 'scheduled__2022-01-26T12:00:00+00:00', '--job-id', '9214', '--raw', '--subdir', 'DAGS_FOLDER/raizen_lab_01.py', '--cfg-path', '/tmp/tmpl6j2ly2c', '--error-file', '/tmp/tmp5n7a8qnq']
[2022-08-23 19:31:57,373] {standard_task_runner.py:80} INFO - Job 9214: Subtask conecta_no_mysql
[2022-08-23 19:31:57,482] {task_command.py:371} INFO - Running <TaskInstance: raizen_lab_01.conecta_no_mysql scheduled__2022-01-26T12:00:00+00:00 [running]> on host d7b3354bd9d0
[2022-08-23 19:31:57,641] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=raizen_lab_01
AIRFLOW_CTX_TASK_ID=conecta_no_mysql
AIRFLOW_CTX_EXECUTION_DATE=2022-01-26T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-26T12:00:00+00:00
[2022-08-23 19:32:07,655] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/raizen_lab_01.py", line 35, in conecta_no_mysql
    con = MySQLdb.connect(host="mysql", user="user", passwd="password", db="db")
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'mysql' (-3)")
[2022-08-23 19:32:07,680] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=raizen_lab_01, task_id=conecta_no_mysql, execution_date=20220126T120000, start_date=20220823T193157, end_date=20220823T193207
[2022-08-23 19:32:07,701] {standard_task_runner.py:97} ERROR - Failed to execute job 9214 for task conecta_no_mysql ((2005, "Unknown MySQL server host 'mysql' (-3)"); 142)
[2022-08-23 19:32:07,751] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-23 19:32:07,807] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
