[2022-08-23 22:56:54,368] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.06_cria_tabela manual__2022-08-23T22:55:52.367021+00:00 [queued]>
[2022-08-23 22:56:54,376] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.06_cria_tabela manual__2022-08-23T22:55:52.367021+00:00 [queued]>
[2022-08-23 22:56:54,377] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 22:56:54,377] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-08-23 22:56:54,378] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 22:56:54,390] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): 06_cria_tabela> on 2022-08-23 22:55:52.367021+00:00
[2022-08-23 22:56:54,396] {standard_task_runner.py:52} INFO - Started process 127 to run task
[2022-08-23 22:56:54,399] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'raizen_lab_01', '06_cria_tabela', 'manual__2022-08-23T22:55:52.367021+00:00', '--job-id', '9461', '--raw', '--subdir', 'DAGS_FOLDER/raizen_lab_01.py', '--cfg-path', '/tmp/tmphu5ob2ee', '--error-file', '/tmp/tmp2vot_7s1']
[2022-08-23 22:56:54,400] {standard_task_runner.py:80} INFO - Job 9461: Subtask 06_cria_tabela
[2022-08-23 22:56:54,462] {task_command.py:371} INFO - Running <TaskInstance: raizen_lab_01.06_cria_tabela manual__2022-08-23T22:55:52.367021+00:00 [running]> on host 25dd15f8d678
[2022-08-23 22:56:54,523] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=raizen_lab_01
AIRFLOW_CTX_TASK_ID=06_cria_tabela
AIRFLOW_CTX_EXECUTION_DATE=2022-08-23T22:55:52.367021+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-23T22:55:52.367021+00:00
[2022-08-23 22:56:54,539] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/raizen_lab_01.py", line 35, in cria_tabela
    con.select_db('select * from tabela_de_deus')
MySQLdb.OperationalError: (1049, "Unknown database 'select * from tabela_de_deus'")
[2022-08-23 22:56:54,554] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=raizen_lab_01, task_id=06_cria_tabela, execution_date=20220823T225552, start_date=20220823T225654, end_date=20220823T225654
[2022-08-23 22:56:54,565] {standard_task_runner.py:97} ERROR - Failed to execute job 9461 for task 06_cria_tabela ((1049, "Unknown database 'select * from tabela_de_deus'"); 127)
[2022-08-23 22:56:54,572] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-23 22:56:54,611] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
